### PR TITLE
Site Redesign

### PR DESCRIPTION
**Pull request by gauravtamhan**
Pull request for my changes.

### CODE REVIEW

**Comment by calda** [comment]
Thank you so much for doing this!!! I ***love*** the new look, and it's so nice to see the tutorials and schedule match the style of the main site.

I'd like to see a few changes before we merge it in:
- For the persistent title at the top left, can you change it to "GT iOS Club" and use [our logo](http://www.iosgatech.xyz/images/home/logo.png) instead of the App Store logo. (same for the site favicon, it should be our logo)
- The "A Special Thanks" section on `index` feels really heavy compared to the rest of the site. Can you tone down the background image, and also make the section a bit smaller (it takes up a lot of vertical space).
- For the schedule screen, can you have it stay as one column? The wrapping makes the chronological order feel weird.
- For the past schedules, instead of fading the entire block, can you just just fade the red dates? It's difficult to read the old schedules when their entire block is faded.

Again, thanks so much for doing this!! I'll merge your redesign after you tidy up some of these small details.

**Comment by gauravtamhan** [comment]
Glad I could help!

* Yup I can definitely change the site title and the logo. Those were just acting as place holders really. Although I did like the finder icon as the favicon haha.
* I can reduce the vertical spacing for the special thanks section but I’m not really sure how to tone down the background image. I’m open to suggestions tho!
* The schedule screen is going to have to stay as a 2 column view on large screen sizes. The initial idea was to maximize screen space and limit the need to scroll down when you have horizontal screen real estate.
* For past schedules, the idea was to make the older schedules quickly and largely discernible from the active schedule. I can reduce the overall amount of fade to increase readability but just having the dates fade looked off when I had originally tried it. Another potential option would be to just remove the fade altogether.

**Comment by gauravtamhan** [comment]
**Changelog**
* Updated site title and logos
* Replaced the special thanks section with a bar of sponsors
* Removed past schedule fade

**Comment by calda** [comment]
Thank you for doing this! I'll go ahead and mere now.

Really appreciate your help

**Comment by calda** [comment]
@gauravtamhan When I merged the PR and viewed the new site on prod, none of the assets were loading.

screenshot 2017-12-29 at 10 25 32 pm

For example, it was trying to load `http://www.iosgatech.xyz/www.iosgatech.xyz/images/home/facebook.jpg`.

I patched it by changing `baseUrl` to an empty string in the `_config.yml`, but that broke the top left GT iOS Club button (no longer routes to `index`). Can you make a quick PR that patches that?

Thanks!

**Pull request merged**
