### PR TITLE
Added google analytics and site description for SEO

### PR DESCRIPTION
**Pull request by gauravtamhan**

### CODE REVIEW

**Comment by calda** [comment]
What Google Analytics account is this feeding into?

**Comment by gauravtamhan** [comment]
It’s linked to a project for which my personal google account has access. I can add others to view and edit as well and even transfer ownership if y’all have a master account for the site.

**Comment by calda** [comment]
Not interested in adding Google Analytics

**Comment by gauravtamhan** [comment]
I was just curious to see the site traffic. It can be on any account if that’s an issue? Just wondering why you’re against it.

**Comment by calda** [comment]
We could perhaps set it up with our iOS Club Google account, but I'm not available to configure that at the moment. cc @brianwang9100

**Pull request closed without merging**
